# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "scarabisterre"
license = "MIT"
licenselink = ""
description = "An academic theme for websites."
homepage = "https://github.com/miwy/scarabisterre"
tags = ["academic", "basic"]
features = ["posts", "publications"]
min_version = 0.58

[author]
  name = "Michał Wyrwa"
  homepage = "http://miwy.github.io/"
